### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by iamskok** [sathify/CCSS#8]
What naming conventions do you use for functions, placeholders and mixins ?

**Comment by sathify** [comment]
@Skoks you brought up a good point. These are the three mixin file examples in the repo for [bem](https://github.com/sathify/CCSS/blob/master/styles/scss/mixins/_bem.scss), [icons](https://github.com/sathify/CCSS/blob/master/styles/scss/mixins/_icon.scss) and [animations](https://github.com/sathify/CCSS/blob/master/styles/scss/mixins/_animation.scss). Didn't really formalize it but start with lowercase and camelcase the second if it has one. In general, I would avoid using `-` to separate names.

**Comment by iamskok** [comment]
@sathify Thanks for your answer. 
That will be a good adding to your article, because there are often times, when placeholders, mixins and functions are longer than 1 word. 

What about naming long file names ? Do you use the same methodology ?

**Comment by sathify** [comment]
@Skoks will add it. It shouldn't really matter in the file naming case: you can user use camelcase or `-` to separate out names.

**Comment by iamskok** [comment]
Is there any reason behind using delimiters for variable names instead of camelCase ? 

@sathify Thank you!  :+1:

**Comment by sathify** [comment]
Nothing really! The repo naming convention had delimiters which I then refactored.
